#!/usr/bin/env python3
"""Derive standard-14 PDF font width tables from groff's devps metrics.

groff's devps font files are generated by `afmtodit` straight from Adobe's
original AFM files (the copyright header is preserved in each), so the widths
are authoritative rather than recalled. Each charset line looks like:

    A<TAB>722,674<TAB>2<TAB>65<TAB>A<TAB>--<TAB>0041
    ^name    ^metrics   ^type ^code ^psname   ^unicode

Field 2's first comma-separated value is the advance width in 1/1000 em.
We key on the PostScript glyph name (field 5) and map it to a WinAnsiEncoding
byte, because WinAnsi is what the writer will declare on its /Font objects.
"""
import os, sys, re

DEVPS = "/usr/share/groff/1.24.1/font/devps"

# The standard 14, in the order bayan will number them.
FONTS_SRC = [
    ("Helvetica",             "HR"),
    ("Helvetica-Bold",        "HB"),
    ("Helvetica-Oblique",     "HI"),
    ("Helvetica-BoldOblique", "HBI"),
    ("Times-Roman",           "TR"),
    ("Times-Bold",            "TB"),
    ("Times-Italic",          "TI"),
    ("Times-BoldItalic",      "TBI"),
    ("Courier",               "CR"),
    ("Courier-Bold",          "CB"),
    ("Courier-Oblique",       "CI"),
    ("Courier-BoldOblique",   "CBI"),
    ("Symbol",                "S"),
    ("ZapfDingbats",          "ZD"),
]


def winansi_map():
    """WinAnsiEncoding byte -> PostScript glyph name.

    WinAnsi is CP1252 with a few Adobe-specific spellings. Derive the bulk from
    Python's cp1252 codec + the Adobe Glyph List basics, then patch the handful
    of names where Adobe and Unicode names differ.
    """
    # Unicode codepoint -> Adobe glyph name, for everything CP1252 can reach.
    uni2name = {}
    # ASCII range names per the Adobe standard.
    ascii_names = {
        0x20: "space", 0x21: "exclam", 0x22: "quotedbl", 0x23: "numbersign",
        0x24: "dollar", 0x25: "percent", 0x26: "ampersand", 0x27: "quotesingle",
        0x28: "parenleft", 0x29: "parenright", 0x2A: "asterisk", 0x2B: "plus",
        0x2C: "comma", 0x2D: "hyphen", 0x2E: "period", 0x2F: "slash",
        0x3A: "colon", 0x3B: "semicolon", 0x3C: "less", 0x3D: "equal",
        0x3E: "greater", 0x3F: "question", 0x40: "at",
        0x5B: "bracketleft", 0x5C: "backslash", 0x5D: "bracketright",
        0x5E: "asciicircum", 0x5F: "underscore", 0x60: "grave",
        0x7B: "braceleft", 0x7C: "bar", 0x7D: "braceright", 0x7E: "asciitilde",
    }
    digits = ["zero", "one", "two", "three", "four", "five",
              "six", "seven", "eight", "nine"]
    for i, d in enumerate(digits):
        uni2name[0x30 + i] = d
    for c in range(0x41, 0x5B):
        uni2name[c] = chr(c)
    for c in range(0x61, 0x7B):
        uni2name[c] = chr(c)
    uni2name.update(ascii_names)

    # Latin-1 + CP1252 upper range, by Adobe glyph name.
    upper = {
        0x00A0: "space", 0x00A1: "exclamdown", 0x00A2: "cent", 0x00A3: "sterling",
        0x00A4: "currency", 0x00A5: "yen", 0x00A6: "brokenbar", 0x00A7: "section",
        0x00A8: "dieresis", 0x00A9: "copyright", 0x00AA: "ordfeminine",
        0x00AB: "guillemotleft", 0x00AC: "logicalnot", 0x00AD: "hyphen",
        0x00AE: "registered", 0x00AF: "macron", 0x00B0: "degree",
        0x00B1: "plusminus", 0x00B2: "twosuperior", 0x00B3: "threesuperior",
        0x00B4: "acute", 0x00B5: "mu", 0x00B6: "paragraph", 0x00B7: "periodcentered",
        0x00B8: "cedilla", 0x00B9: "onesuperior", 0x00BA: "ordmasculine",
        0x00BB: "guillemotright", 0x00BC: "onequarter", 0x00BD: "onehalf",
        0x00BE: "threequarters", 0x00BF: "questiondown",
        0x00C0: "Agrave", 0x00C1: "Aacute", 0x00C2: "Acircumflex", 0x00C3: "Atilde",
        0x00C4: "Adieresis", 0x00C5: "Aring", 0x00C6: "AE", 0x00C7: "Ccedilla",
        0x00C8: "Egrave", 0x00C9: "Eacute", 0x00CA: "Ecircumflex", 0x00CB: "Edieresis",
        0x00CC: "Igrave", 0x00CD: "Iacute", 0x00CE: "Icircumflex", 0x00CF: "Idieresis",
        0x00D0: "Eth", 0x00D1: "Ntilde", 0x00D2: "Ograve", 0x00D3: "Oacute",
        0x00D4: "Ocircumflex", 0x00D5: "Otilde", 0x00D6: "Odieresis",
        0x00D7: "multiply", 0x00D8: "Oslash", 0x00D9: "Ugrave", 0x00DA: "Uacute",
        0x00DB: "Ucircumflex", 0x00DC: "Udieresis", 0x00DD: "Yacute",
        0x00DE: "Thorn", 0x00DF: "germandbls",
        0x00E0: "agrave", 0x00E1: "aacute", 0x00E2: "acircumflex", 0x00E3: "atilde",
        0x00E4: "adieresis", 0x00E5: "aring", 0x00E6: "ae", 0x00E7: "ccedilla",
        0x00E8: "egrave", 0x00E9: "eacute", 0x00EA: "ecircumflex", 0x00EB: "edieresis",
        0x00EC: "igrave", 0x00ED: "iacute", 0x00EE: "icircumflex", 0x00EF: "idieresis",
        0x00F0: "eth", 0x00F1: "ntilde", 0x00F2: "ograve", 0x00F3: "oacute",
        0x00F4: "ocircumflex", 0x00F5: "otilde", 0x00F6: "odieresis",
        0x00F7: "divide", 0x00F8: "oslash", 0x00F9: "ugrave", 0x00FA: "uacute",
        0x00FB: "ucircumflex", 0x00FC: "udieresis", 0x00FD: "yacute",
        0x00FE: "thorn", 0x00FF: "ydieresis",
        # CP1252 0x80-0x9F block
        0x20AC: "Euro", 0x201A: "quotesinglbase", 0x0192: "florin",
        0x201E: "quotedblbase", 0x2026: "ellipsis", 0x2020: "dagger",
        0x2021: "daggerdbl", 0x02C6: "circumflex", 0x2030: "perthousand",
        0x0160: "Scaron", 0x2039: "guilsinglleft", 0x0152: "OE", 0x017D: "Zcaron",
        0x2018: "quoteleft", 0x2019: "quoteright", 0x201C: "quotedblleft",
        0x201D: "quotedblright", 0x2022: "bullet", 0x2013: "endash",
        0x2014: "emdash", 0x02DC: "tilde", 0x2122: "trademark",
        0x0161: "scaron", 0x203A: "guilsinglright", 0x0153: "oe",
        0x017E: "zcaron", 0x0178: "Ydieresis",
    }
    uni2name.update(upper)

    out = {}
    for b in range(32, 256):
        try:
            ch = bytes([b]).decode("cp1252")
        except UnicodeDecodeError:
            continue
        cp = ord(ch)
        if cp in uni2name:
            out[b] = uni2name[cp]
    return out


def read_font(tag):
    """groff devps file -> {ps_glyph_name: width}, plus {builtin_code: width}."""
    path = os.path.join(DEVPS, tag)
    by_name, by_code = {}, {}
    with open(path, "r", encoding="latin-1") as f:
        lines = f.read().splitlines()
    try:
        i = lines.index("charset")
    except ValueError:
        raise SystemExit(f"{path}: no charset section")
    for line in lines[i + 1:]:
        if not line.strip():
            continue
        parts = line.split("\t")
        # A comment starts with '#' — but so does the charset line for the
        # numbersign GLYPH itself ("#<TAB>556,688<TAB>2<TAB>35<TAB>numbersign").
        # Skipping every '#' line silently drops '#' from all 12 text fonts.
        # Discriminate on structure, not on the first byte.
        if len(parts) < 4:
            continue
        # A continuation line ('"' metrics) aliases the previous glyph.
        if parts[1].strip() == '"':
            continue
        metrics = parts[1].split(",")
        try:
            width = int(metrics[0])
        except ValueError:
            continue
        try:
            code = int(parts[3])
        except (ValueError, IndexError):
            code = -1
        psname = parts[4].strip() if len(parts) > 4 else parts[0]
        if psname and psname != "---":
            by_name.setdefault(psname, width)
        else:
            by_name.setdefault(parts[0], width)
        if 0 <= code < 256:
            by_code.setdefault(code, width)
    return by_name, by_code



ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
assert len(ALPHA) == 64

SUFFIX = [
    "helv", "helv_b", "helv_o", "helv_bo",
    "times", "times_b", "times_i", "times_bi",
    "cour", "cour_b", "cour_o", "cour_bo",
    "symbol", "zapf",
]
COURIER = {"Courier", "Courier-Bold", "Courier-Oblique", "Courier-BoldOblique"}

def enc(widths):
    out = []
    for b in range(32, 256):
        w = widths[b]
        if not 0 <= w < 4096:
            raise SystemExit(f"width {w} out of encodable range")
        out.append(ALPHA[(w >> 6) & 63])
        out.append(ALPHA[w & 63])
    return "".join(out)


def winansi_block():
    """The WinAnsi 0x80-0x9F block as Unicode codepoints, 3 base64 chars each.

    WinAnsiEncoding is CP1252. Bytes 0xA0-0xFF map to U+00A0-U+00FF identically
    (verified: zero non-identity mappings), and 0x00-0x7F is ASCII, so the ONLY
    part needing a table is the 32-entry 0x80-0x9F block. Five of those codes
    are undefined in CP1252 -- 0x81 0x8D 0x8F 0x90 0x9D -- and are emitted as 0.

    Max codepoint in the block is U+2122 (8482), which exceeds 64^2, so each
    entry takes three base64 characters rather than the two a width uses.
    """
    out = []
    for b in range(0x80, 0xA0):
        try:
            cp = ord(bytes([b]).decode("cp1252"))
        except UnicodeDecodeError:
            cp = 0
        if cp >= 64 ** 3:
            raise SystemExit(f"codepoint {cp} too large for 3 base64 chars")
        out.append(ALPHA[(cp >> 12) & 63])
        out.append(ALPHA[(cp >> 6) & 63])
        out.append(ALPHA[cp & 63])
    return "".join(out)


def build_tables():
    """Derive, then self-verify, the 14 standard font width tables."""
    wmap = winansi_map()
    tables = {}
    for psfont, tag in FONTS_SRC:
        by_name, by_code = read_font(tag)
        widths = [0] * 256
        if psfont in ("Symbol", "ZapfDingbats"):
            # These carry their own built-in encoding, not WinAnsi.
            for c, w in by_code.items():
                widths[c] = w
        else:
            for b, name in wmap.items():
                if name in by_name:
                    widths[b] = by_name[name]
        tables[psfont] = widths

    # --- verification: documented, stable Adobe widths ---
    checks = [
        ("Helvetica", " ", 278), ("Helvetica", "A", 667), ("Helvetica", "!", 278),
        ("Helvetica", "#", 556), ("Helvetica", "W", 944), ("Helvetica", "i", 222),
        ("Helvetica", "m", 833),
        ("Helvetica-Bold", "A", 722), ("Helvetica-Bold", " ", 278),
        ("Times-Roman", "A", 722), ("Times-Roman", " ", 250),
        ("Times-Roman", "i", 278), ("Times-Roman", "W", 944), ("Times-Roman", "#", 500),
        ("Times-Bold", "A", 722), ("Times-Italic", "A", 611),
        ("Courier", "A", 600), ("Courier", " ", 600), ("Courier", "i", 600),
        ("Courier", "W", 600), ("Courier", "#", 600), ("Courier-Bold", "A", 600),
    ]
    bad = [f"  {f}[{c!r}] = {tables[f][ord(c)]}, expected {w}"
           for f, c, w in checks if tables[f][ord(c)] != w]
    if bad:
        raise SystemExit("WIDTH CHECK FAILED:\n" + "\n".join(bad))
    print(f"width checks passed ({len(checks)} spot values)", file=sys.stderr)

    for f in ("Courier", "Courier-Bold", "Courier-Oblique", "Courier-BoldOblique"):
        nz = {w for w in tables[f] if w}
        if nz != {600}:
            raise SystemExit(f"{f} is not monospace 600: {sorted(nz)}")
    print("Courier family verified monospace 600", file=sys.stderr)

    for f, _ in FONTS_SRC:
        n = sum(1 for w in tables[f] if w)
        print(f"  {f:24s} {n:3d}/224 WinAnsi codes covered", file=sys.stderr)
    return tables


def main():
    tables = build_tables()
    out = []
    emit = out.append
    emit("# --- Standard-14 font metrics -------------------------------------")
    emit("#")
    emit("# Advance widths in 1/1000 em, WinAnsiEncoding-indexed, derived from")
    emit("# Adobe's original AFM metrics (via groff's afmtodit-generated devps")
    emit("# font files) and verified against 22 documented spot widths plus a")
    emit("# whole-family monospace check.")
    emit("#")
    emit("# GENERATED by scripts/gen-widths.py — do not hand-edit.")
    emit("#")
    emit("# Each width is two base64-alphabet characters (high 6 bits, low 6")
    emit("# bits) covering codes 32..255 = 448 characters per font. Codes 0..31")
    emit("# are control characters and carry no glyph. The Courier family is")
    emit("# uniformly 600 at every code, so it is answered arithmetically by")
    emit("# _pdf_font_width rather than tabled.")
    emit("")
    n = 0
    for (name, _), sfx in zip(FONTS_SRC, SUFFIX):
        if name in COURIER:
            continue
        n += 1
        emit(f"# {name}")
        emit(f'var _PDF_W_{sfx.upper()} = "{enc(tables[name])}";'
             '  #skip-lint: generated data table, one literal, not wrappable')
        emit("")
    emit(f"# {n} tabled fonts; the 4 Courier faces are constant-600.")
    emit("")
    emit("# --- WinAnsiEncoding <-> Unicode --------------------------------")
    emit("#")
    emit("# Only the 0x80..0x9F block needs a table: 0x00..0x7F is ASCII and")
    emit("# 0xA0..0xFF is Latin-1 identity (verified: zero non-identity maps).")
    emit("# Three base64 chars per entry (max is U+2122, which exceeds 64^2).")
    emit("# The five CP1252 holes 0x81 0x8D 0x8F 0x90 0x9D are emitted as 0.")
    wb = winansi_block()
    emit(f'var _PDF_WINANSI_HI = "{wb}";'
         '  #skip-lint: generated data table, one literal, not wrappable')

    # Round-trip: decode what we just emitted and compare against the source.
    idx = {c: i for i, c in enumerate(ALPHA)}
    text = "\n".join(out)
    mism = 0
    for m in re.finditer(r'var _PDF_W_(\w+) = "([^"]*)";', text):
        name = dict(zip([s.upper() for s in SUFFIX],
                        [f for f, _ in FONTS_SRC]))[m.group(1)]
        s = m.group(2)
        if len(s) != 448:
            raise SystemExit(f"{name}: emitted {len(s)} chars, expected 448")
        for k in range(224):
            if idx[s[2 * k]] * 64 + idx[s[2 * k + 1]] != tables[name][32 + k]:
                mism += 1
    if mism:
        raise SystemExit(f"round-trip FAILED: {mism} mismatches")
    print(f"round-trip verified: {n} tables, 0 mismatches", file=sys.stderr)

    wb = winansi_block()
    if len(wb) != 96:
        raise SystemExit(f"WinAnsi block is {len(wb)} chars, expected 96")
    for k in range(32):
        cp = idx[wb[3*k]] * 4096 + idx[wb[3*k+1]] * 64 + idx[wb[3*k+2]]
        b = 0x80 + k
        try:
            want = ord(bytes([b]).decode("cp1252"))
        except UnicodeDecodeError:
            want = 0
        if cp != want:
            raise SystemExit(f"WinAnsi block mismatch at {hex(b)}: {cp} != {want}")
    print("WinAnsi 0x80-0x9F block verified (32 entries)", file=sys.stderr)

    dest = sys.argv[1] if len(sys.argv) > 1 else None
    if dest:
        with open(dest, "w") as f:
            f.write(text + "\n")
        print(f"wrote {dest}", file=sys.stderr)
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
